runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: tester
  CLOUD_SQL_PASSWORD: testerpass
  CLOUD_SQL_DATABASE_NAME: demo
  CLOUD_SQL_CONNECTION_NAME: advanced-development-with:europe-west2:adproject